### ISSUE TITLE
Update configuration.py template for prometheus_client change

### ISSUE THREAD

**Issue by tyler-8** [lae/ansible-role-netbox#101]
The prometheus_client library had a change back in February that is breaking with the metrics configuration for uwsgi.

https://github.com/prometheus/client_python/pull/514

[This line](https://github.com/lae/ansible-role-netbox/blob/bcab5ba6ec9e4ff123541e8e1ec0d50993d6461e/templates/configuration.py.j2#L11) will need to be changed in one of two ways:

Rename the argument:
```
# Old
_pidFunc=uwsgi.worker_id)
# New
process_identifier=uwsgi.worker_id)
```

or just remove the kwarg altogether as the function only has one possible argument.

```
# Old
_pidFunc=uwsgi.worker_id)
# New
uwsgi.worker_id)
```

**Comment by tyler-8** [comment]
FWIW - I'd like to do the latter as it's version independent.

**Comment by lae** [comment]
Go ahead and use the latter.
