### ISSUE TITLE
Add support for database OPTIONS dictionary

### ISSUE THREAD

**Issue by tyler-8** [lae/ansible-role-netbox#104]
Similar to the discussion in https://github.com/lae/ansible-role-netbox/issues/64 (and realizing I put my own foot in my mouth because here we are) there are some use cases where it's up to the user's environment. In my particular case, I need to set the `sslmode` parameter to something other than the default.

I think the simplest option would be to introduce a new var like:

`netbox_database_options` that would be a dictionary used similar to `netbox_uwsgi_options` and `netbox_config` are already handled today.

For cases like [isolation levels](https://docs.djangoproject.com/en/2.2/ref/databases/#isolation-level) we could add a note that the _real_ numerical value must be used instead of the constant `psycopg2.extensions.ISOLATION_LEVEL_SERIALIZABLE` as specified in the example. It seems like the other [possible options](https://www.postgresql.org/docs/10/libpq-connect.html#LIBPQ-PARAMKEYWORDS) for PostgreSQL are either strings or numbers so the existing logic used for `netbox_config` should work fine here as well.

A quick pass at the template logic

```jinja
DATABASE = {
    'NAME': '{{ netbox_database }}',
    'USER': '{{ netbox_database_user }}',
{% if netbox_database_host is defined %}
    'PASSWORD': '{{ netbox_database_password }}',
    'HOST':  '{{ netbox_database_host }}',
    'PORT': '{{ netbox_database_port }}',
{% else %}
    {% if netbox_database_password is defined %}
    'PASSWORD': '{{ netbox_database_password }}',
    {% endif %}
    'HOST': '{{ netbox_database_socket }}',
{% endif %}
    'CONN_MAX_AGE': {{ netbox_database_conn_age }},
{% if netbox_database_options is defined %}\
    'OPTIONS': {
        {% for setting, value in netbox_database_options.items() %}
        {% if value is string or value is number %}
        "{{ setting }}": {{ value | to_nice_json }},
        {% else %}
        "{{ setting }}": json.loads(r'''{{ value | to_json }}'''),
        {% endif %}
        {% endfor %}
    }
{% endif %}
}
```

**Comment by lae** [comment]
Do you think we can get rid of the `else` statement that inserts `json.loads`? If there are no arrays/dictionaries then it doesn't look like it'd be necessary.

Other than that, what you suggest sounds good to me. Feel free to create a PR and documentation and I'll review it.
