### ISSUE TITLE
Ubuntu 20.04 Focal Fossa support missing

### ISSUE THREAD

**Issue by sleinen** [lae/ansible-role-netbox#105]
I tried to install NetBox on a machine that was upgraded to the latest Ubuntu (LTS) release, and ran into the problem that no OS-specific file such as `vars/ubuntu-20.yml` was found. So I made one, starting from the `ubuntu-18` one. The only modification I made was replacing `python3.6` with `python3.8`, as Focal comes with Python 3.8.  With this new file, I was able to provision a(n apparently) working NetBox installation on my Focal box.

I'm happy to submit a PR. Unfortunately I was unable so far to get Molecule to run the tests on my (Mac OS) development machine, even though I think I have installed all prerequisites.

**Comment by lae** [comment]
See #91 

The PR works, but causes tests across multiple distributions to fail under Travis CI, so it hasn't been merged. I haven't been able to figure out why...

**Comment by sleinen** [comment]
Interesting. When I run my own [branch](https://github.com/lae/ansible-role-netbox/tree/feature/ubuntu-focal) through the pipeline, I see [error messages of the form "unsupported pickle protocol: 5"](https://travis-ci.com/github/sleinen/ansible-role-netbox/jobs/361293476#L6250). That may be due to an incompatibility between Python 3.8 (which is what comes with Ubuntu 20.04) and earlier Python versions: Python 3.8 supports Pickle format 5, earlier versions of Python don't.

I don't know NetBox or the tests well enough to understand where this could become a problem.  I do note that in the NetBox source itself, `pickle.HIGHEST_PROTOCOL` (`5` on Python 3.8, `4` on 3.6) is sometimes used to specify the serialization format instead `pickle.DEFAULT_PROTOCOL` (`4` on Python 3.8). This might cause such interoperability issues.

**Comment by sleinen** [comment]
> I do note that in the NetBox source itself, pickle.HIGHEST_PROTOCOL (5 on Python 3.8, 4 on 3.6) is sometimes used to specify the serialization format instead of pickle.DEFAULT_PROTOCOL (4 on Python 3.8). This might cause such interoperability issues.

Sorry, correction: These mentions of `pickle.HIGHEST_PROTOCOL` aren't in NetBox itself, but rather in some libraries: `django`, `cacheops`, and `rq`.  I'll try to find out which of those (if any) might explain the test failures.

**Comment by lae** [comment]
Yeah. For the record, tests for all distributions work fine on the default branch (there's a regular cron for it to check for breakages and the last build ran successfully 5 days ago). It's only when this definition is added that these pickle errors start occurring - which doesn't make sense to me because they should all be isolated from each other via the LXC containers.

**Comment by lae** [comment]
Resolved via aforementioned PR.
