### ISSUE TITLE
Why is the netbox.socket and netbox.service separated?

### ISSUE THREAD

**Issue by ironiq** [lae/ansible-role-netbox#118]
I try to extend the role and the example playbook to be able to deploy multiple instances. As i could understand the uwsgi configuration i can define the socket inside the ini file. In the current state it's very hard to deploy multiple instances. If the "netbox.socket" unit is skipped, the "netbox.service" is modified a bit and the socket is added to uwsgi.ini, it's easier to create multi-instance netbox.

**Comment by lae** [comment]
Using a socket makes the configuration a bit simpler and lets upgrades to NetBox take place without losing any requests (especially if one opts to not set up a proxy server like nginx in front). I think it also allowed the use of low ports without needing to start NetBox as root and then drop privileges.

One of the design philosophies for NetBox is to serve as a (single) source of truth. I'm of the opinion that if one needs to run two instances of NetBox then they're probably for different organizations (although whether this is appropriate or not is debatable), for running two different environments for testing NetBox itself (staging/prod), or for high availability and thus should really be isolated via a container mechanism like LXC (and in the case of HA, another physical server, which I guess could still be LXC). So I'm unlikely to accept a change that gets rid of the socket/service model for this reason.

I'll let others chime in with their opinion here, maybe I'm missing some other use case.

If it really is necessary to support multi-tenant on the same server, it should be possible to modify the systemd units into template units and thus support multiple profiles via a variable (e.g. `netbox@default.service` and `netbox@default.socket`).

**Comment by ironiq** [comment]
The low port usage and the privilege dropping is reasonable, good idea, i didn't know about this feature in systemd (possible to split the socket creation from the service). 

Regarding the multiple instances: yes, you are right, the separation would be nice (separate VM/container), but this is the request, so i have to solve it somehow. I know the template units, i'm also checking this way. I will see what comes. I was able to solve lots of things in playbook and/or host_vars, but these units were the problematic things.

**Comment by ironiq** [comment]
Haven't checked it later and problem solved with creating new machine for dev.
