### ISSUE TITLE
Netbox 2.11 planning to drop support for python36

### ISSUE THREAD

**Issue by mtinberg** [lae/ansible-role-netbox#127]
https://github.com/netbox-community/netbox/issues/5532

I checked on my CentOS 7 host and rh-python38 exists as a software collection so we should be able to change the package install portion to require that and use it to create the venv `scl enable rh-python38 "python -m venv py38venv"` which may fix some of the other issue with newer cryptography and rust.

I haven't tested on Ubuntu 18.04 and this change is a few months out, hopeful in the interim we can rework the playbook to get the newer python runtime installed on all the platforms where it is readily available.

**Comment by lae** [comment]
Are software collections typically installable out of the box on CentOS? Last I recall they weren't/involved extra administration work to setup installing from software collections, but my memory is hazy.

If not, I'm not sure it would be appropriate to have this role take on the scope of doing so. It might just be best to write documentation/example playbook for deploying to CentOS using another role or something, and have this role test for/expect Python 3.8.

**Comment by mtinberg** [comment]
That's very reasonable, we should just have a constraint check for python38 and have a message with some clue what to do when it's not found

—
Mark Tinberg ***@***.***>
Division of Information Technology-Network Services
University of Wisconsin-Madison


________________________________________

**Comment by lae** [comment]
Fixed in #141
