### ISSUE TITLE
AnsibleUndefinedVariable: {{ ansible_processor_vcpus }} when running role

### ISSUE THREAD

**Issue by jlownie** [lae/ansible-role-netbox#135]
We ran the role (v1.0.2) on a host and got this error message:

ASK [lae.netbox : Configure uWSGI NetBox application] **************************************************************************************************************************************************************************************
fatal: [xxx.sol1.net]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: {{ ansible_processor_vcpus }}: 'ansible_processor_vcpus' is undefined"}

The variable ansible_processor_vcpus isn't referenced in that task but it is referenced in defaults/main.yml:
netbox_processes: "{{ ansible_processor_vcpus }}"

We changed it to this and it worked:
netbox_processes: "{{ ansible_processor_vcpus | default(4) }}"

I'm not sure why that var is undefined - from what I've read it's supposed to be set automatically somewhere.  So I'm not sure if what we've done is the best solution but I'm happy to submit it in a pull request if people think it's OK.

**Comment by lae** [comment]
fixed in https://github.com/lae/ansible-role-netbox/commit/99d3dcad4d63bb155ad223f54e0c39b7190f56ad
