### ISSUE TITLE
Recommended SSL settings

### ISSUE THREAD

**Issue by Qwiko** [lae/ansible-role-netbox#149]
What is the recommended way to enable SSL for netbox?

**Comment by lae** [comment]
The way that fits in with the rest of your environment, but off the top of my head a standard method would just to be to either use LetsEncrypt if facing publicly, or a company-signed/self-signed cert internally, use a vhost in nginx that proxies to Netbox over wsgi.

**Comment by Qwiko** [comment]
I managed this with nginx in front of uwsgi using the guide from netbox.
I was unable to pass the socket directly in nginx and used proxy_pass instead.

**Comment by Qwiko** [comment]
For anyone trying this as well.
This is what worked for me.
Ansible vars:
```
netbox_protocol: uwsgi
netbox_socket: "/tmp/netbox.sock"
```
Change nginx user to netbox in nginx.conf
```
user netbox;
...
```
nginx netbox configuration
```
    location / {
        include         uwsgi_params;
        uwsgi_pass      unix:/tmp/netbox.sock;
    }
```
