### ISSUE TITLE
RQworker reload fails randomly

### ISSUE THREAD

**Issue by p-rintz** [lae/ansible-role-netbox#160]
Hi there,

I have an issue where the reload handler of the rqworker will fail randomly.
It then immediately restarts again and it works, but this behaviour leads to issues in the playbook or Github Actions sometimes failing as they think the service failed completely.

In the logs it looks like this:
```
Jul 24 06:29:47 netbox.dev systemd[1]: Reloading NetBox RQ-Worker...
Jul 24 06:29:47 netbox.dev kill[29022]: Usage:
Jul 24 06:29:47 netbox.dev kill[29022]:  kill [options] <pid> [...]
Jul 24 06:29:47 netbox.dev kill[29022]: Options:
Jul 24 06:29:47 netbox.dev kill[29022]:  <pid> [...]            send signal to every <pid> listed
Jul 24 06:29:47 netbox.dev kill[29022]:  -<signal>, -s, --signal <signal>
Jul 24 06:29:47 netbox.dev kill[29022]:                         specify the <signal> to be sent
Jul 24 06:29:47 netbox.dev kill[29022]:  -q, --queue <value>    integer value to be sent with the signal
Jul 24 06:29:47 netbox.dev kill[29022]:  -l, --list=[<signal>]  list all signal names, or convert one to a name
Jul 24 06:29:47 netbox.dev kill[29022]:  -L, --table            list all signal names in a nice table
Jul 24 06:29:47 netbox.dev kill[29022]:  -h, --help     display this help and exit
Jul 24 06:29:47 netbox.dev kill[29022]:  -V, --version  output version information and exit
Jul 24 06:29:47 netbox.dev kill[29022]: For more details see kill(1).
Jul 24 06:29:47 netbox.dev systemd[1]: netbox-rqworker.service: Control process exited, code=exited, status=1/FAILURE
Jul 24 06:29:47 netbox.dev systemd[1]: netbox-rqworker.service: Failed with result 'exit-code'.
Jul 24 06:29:47 netbox.dev systemd[1]: Reload failed for NetBox RQ-Worker.
```

Is there a specific reason why a reload is done instead of a normal restart?

Switching to the (by now) default [netbox-rq.service](https://github.com/netbox-community/netbox/blob/develop/contrib/netbox-rq.service) file might be a solution.

I implemented #129 in https://github.com/lae/ansible-role-netbox/pull/161 which should fix this issue as well.

**Comment by lae** [comment]
> Is there a specific reason why a reload is done instead of a normal restart?

Conventionally, reloads are meant to refresh running services without interruption, which I assume is the intention here. But I guess it might not be applicable to this service since it's not user-facing, so a normal restart should be fine?

**Comment by lae** [comment]
Reloads replaced with restarts in #161
