### ISSUE TITLE
Outdated Version on Ansible-Galaxy

### ISSUE THREAD

**Issue by ju6ge** [lae/ansible-role-netbox#176]
The Package on Ansible-Galaxy is still referring to version 1.0.4 as the latest release. While on Github the newest release is 1.0.6. Would be great if this could be updated, because 1.0.4 does not include the variables for debian 12.

Thanks for your great work ;)

**Comment by lae** [comment]
This is mentioned in the release notes and there's a forum thread about it.

https://github.com/lae/ansible-role-netbox/discussions/174

No one from Ansible has provided a workaround, and it's not my responsibility to fix it.

**Comment by ju6ge** [comment]
Hey,

so I have hit this issue because when using the galaxy role in combination with newer versions of debian the variables are not detected properly. To resolve this a newer version of the role is required. Sadly the instructions on #174 are also false. The url specified does not point to this repository.

So for anybody wanting to use the newest version of this role the following definition in `requirements.yml` should do the trick:

```yaml
  - name: lae.netbox
    scm: git
    src: https://github.com/lae/ansible-role-netbox.git
    version: v1.0.7

```
