### ISSUE TITLE
Write out requirements installed by the role to local_requirements.txt first

### ISSUE THREAD

**Issue by sol1-matt** [lae/ansible-role-netbox#193]
The role installs a number of components into the venv directly, this means the on disk config is out of sync with the installed config (but in sync with the ansible config).

This prevents the use of the built in Netbox `./upgrade.sh` (which is a handly "reset" for many Netbox problems) and can make troubleshooting harder.

Any objections to writing out the [Install selected optional Python dependencies](https://github.com/lae/ansible-role-netbox/blob/fea39ad80c4c222634fc7d33eef3cf8a70f8c9ba/tasks/deploy_netbox.yml#L73) task to a local_requirements.txt file first @lae ?

**Comment by lae** [comment]
Yeah, I think this is okay to implement. It looks like it's ignored by `.gitignore` so it shouldn't pose a problem to drop this in `netbox_current_path`, which is where it has to go for `./upgrade.sh` to work if I understand correctly.

It doesn't seem necessary to update the linked task to use the file so probably best to leave it alone, and just add a task to place that file/template.

**Comment by sol1-matt** [comment]
added this feature [here](https://github.com/sol1-matt/ansible-role-netbox/commit/31aa7872619fffabcbda121393b64f6ebcd64d6b) for testing

I'm choosing to write the the file directly to the current directory as the `local_requirements.txt` tend to be tied tightly to `base_requirements.txt`, particularly when dealing with python social auth, so being able to look back at what a previous version had is beneficial during upgrades.

**Comment by lae** [comment]
That is indeed another benefit but what other option did you have in mind...?

From an initial glance that diff looks fine, except for the handlers. The file doesn't get touched by runtime and the handlers are already on the install task so it's redundant in some sense.

**Comment by sol1-matt** [comment]
I've could have put the `local_requirements.txt` in `shared` them symlinked it to the current Netbox.

When I've used shared with a symlink in the past and things go wonky, python social auth dependent library versions can be annoying, it is nice to be able to see what the previous versions used (particularly if you go on holidays and 'others' decide that is the perfect time to update a Netbox with complex SSO library dependencies 👀) which isn't the case with a current dir version of the file.

**Comment by lae** [comment]
Oh okay, I actually wasn't thinking of doing that when I made https://github.com/lae/ansible-role-netbox/issues/193#issuecomment-2510331762 for some reason so I was like "wait, but putting it there was what I was suggesting anyway" lol
