### ISSUE TITLE
strange errorcode when migrating netbox database

### ISSUE THREAD

**Issue by Side2005** [lae/ansible-role-netbox#35]
[gist link ](https://gist.github.com/Side2005/d202c6b02f6238a816916436fd4557a1)

**Comment by lae** [comment]
Can you post the contents of `/srv/netbox/shared/configuration.py` here? I want to double check if there's a documentation error.

Also, if you run `ansible-playbook` with `ANSIBLE_STDOUT_CALLBACK=debug` the error output should be more readable.

**Comment by Side2005** [comment]
Hey lae, thanks for your reply!
Im quiet new to git and ansible, im happy about every suggestion i do get.

Here is the [requested configuration.py](https://gist.github.com/Side2005/939665b2a1be45edc4aeba5c3874ed6a) link, sourced from my `ubuntu 18.04.1"fn-lan-s001"` server in `/srv/netbox/shared/configuration.py`

Adding `ANSIBLE_STDOUT_CALLBACK=debug` to my playbook/ansible.cfg didn't change anything, i'm looking into more information about this flag. Thanks for mentioning it!

Offtopic: I'd be happy about every source of information about best practices in git, ansible, gist etc. you can find/send :)

**Comment by lae** [comment]
Did you change yours vars after creating your gist by any chance? I wasn't expecting the config to be connecting to postgres on localhost:5432 via TCP.

Just making sure, but `ANSIBLE_STDOUT_CALLBACK` is an environment variable so you should be using it like:

`ANSIBLE_STDOUT_CALLBACK=debug ansible-playbook -i inventory_file playbook.yml`

**Comment by Side2005** [comment]
Because I lost track of the overall view I now recreated everything from scratch and used your example `playbook_single_host_deploy.yml` to deploy my instance- running against a freshyl installed `ubuntu 18.04.1` VM hosted by VMWare Workstation V.14.

Now im running the following [commit](https://github.com/Side2005/ansible_test/tree/77766bcf53a2d95465ee28210c1525a03ba38d66) from origin/master against my VM.

After adding the flag to my playbook I do [get a very comprehensable errorcode](https://gist.github.com/Side2005/6732f00ea72a809d1837677c3ed01700) (again, thanks alot!)

After checking my postgresql users and tables I do get the following: [Postgresql return](https://gist.github.com/Side2005/e4c4bec0eeef360a3168c42beca19f78)

Looks like the creation of correct database user/table failed?

**Comment by Side2005** [comment]
After manually editing users postgresql's pw with `sudo passwd postgres`, adding `postgres` as my default password and editing ` ansible_test/inventory/staging/group_vars/netbox.yml` with the following [changes](https://github.com/Side2005/ansible_test/commit/cee521173b3a0dd81d8ed7891386213551b67f1a) 
I now get the following [error](https://gist.github.com/Side2005/b16d0485058449878111212e4dda992b).

Now i also have a new [configuration.py](https://gist.github.com/Side2005/251c88f4b968f47cc1468765f3fb4958) in directory `/srv/netbox/shared/`.

**Comment by lae** [comment]
I'll have to follow up on this once I'm back in the states (I'm flying out of Japan on Tuesday).

**Comment by lae** [comment]
I just took a quick look at the NetBox mailing list and it seems you're not the only one with the problem → https://groups.google.com/forum/#!topic/netbox-discuss/C6mV6RIqn-M

i was thinking it might be related to the Django version that was installed, which I would need to attempt a test deployment I can interact with first to fiddle around with.

**Comment by lae** [comment]
I probably should have asked, but I had assumed you emptied the `SECRET_KEY` in the `configuration.py` that you posted earlier. I guess the playbook *is* actually leaving that empty on Ubuntu 18, which happens to cause the migration error (I just set it to something random and `manage.py migrate` worked fine).

Going to look into what's causing the `SECRET_KEY` to not be set.

**Comment by lae** [comment]
```
netbox@ubuntu1804:~$ ./current/netbox/generate_secret_key.py | tr -d $'\n'
/usr/bin/env: 'python': No such file or directory
netbox@ubuntu1804:~$ echo $?
0
```
Okay, it looks like it has to do with the fact that Python 2 isn't installed but the role tries to execute that script directly. The error code from Python is eaten up by the piped `tr` so that's why the `SECRET_KEY` generation task itself doesn't fail.
