### ISSUE TITLE
Add example playbook with Redis/webhooks enabled

### ISSUE THREAD

**Issue by lae** [lae/ansible-role-netbox#39]
Readme currently suggests a Redis role, but doesn't provide some quick pointers to get off the ground with that role. An example playbook should be included in `examples/` demonstrating how to use it, briefly.

**Comment by madeinoz67** [comment]
@lae assign this to me as I'll do with #37 fix

**Comment by lae** [comment]
weird, I can't assign to you for some reason

**Comment by madeinoz67** [comment]
:ghost::ghost:...welcome to the twilight zone...:ghost::ghost:

**Comment by lae** [comment]
I think I need to actually add you as a collaborator in order to assign anything iirc (there's probably an exception if you open an issue)
