### ISSUE TITLE
Python 3.5 is the minimum supported for Django 2.1

### ISSUE THREAD

**Issue by lae** [lae/ansible-role-netbox#41]
Release notes: https://docs.djangoproject.com/en/2.1/releases/2.1/

NetBox 2.5 depends on Django 2.1 now, which breaks builds for CentOS/RHEL 7 (see #40) and likely also Debian 8.

I think we should still support CentOS 7, but maybe drop support for Debian 8 (since we already have 9).

Since the latest in CentOS 3.4, it looks like it might be necessary to use a third-party repo. Is https://ius.io/ the recommended one?

**Comment by madeinoz67** [comment]
definitely support Centos, best to use EPEL <https://fedoraproject.org/wiki/EPEL> repos

**Comment by lae** [comment]
Yeah, I used EPEL. This issue is actually resolved in the PR/commits referenced earlier, just has not hit master.
