### ISSUE TITLE
Django Migration issue on First run

### ISSUE THREAD

**Issue by hkdanalyser** [lae/ansible-role-netbox#45]
I am running into an issue when the Django migrate task runs. This is for a brand new installation.

Centos 7.4
Python 3.6
Ansible 2.7.5

The gist of the issue has been added here.
https://gist.github.com/hkdanalyser/1851b2b694fd3792d14cf2a900d47314

The config for the ansible role is here 
https://gist.github.com/hkdanalyser/700876920c7905854e39bd527b961afc

Any insight would be appreciated. 

Thanks !

**Comment by lae** [comment]
This looks like a PostgreSQL issue. I see that PG10 is listed in your playbook vars, but can you double check what version is installed? `postgres --version`

**Comment by lae** [comment]
@hkdanalyser Also, is it possible that you originally had an older version of PostgreSQL installed and running that is still running/needs migrations to PG10?

**Comment by lae** [comment]
I'm assuming this issue was opened by the person who opened [this thread](https://groups.google.com/forum/#!topic/netbox-discuss/Td6-XQT3irQ) on netbox-discuss, which seems to be resolved, so I'm closing this. If you're not the same person/still have this issue, feel free to reopen.
