### ISSUE TITLE
Upgrade of psycopg2 dependency fails

### ISSUE THREAD

**Issue by madeinoz67** [lae/ansible-role-netbox#51]
I've been away on leave and when I returned last week I bumped netbox to the latest version, low and behold its failed to deploy psycopg2 python package, where before its been fine.

It appears that pg_config can't be found  when pip goes to install psycopg2.  Looking back at my previous successful deploys it was using v0.7.6 of this role.  changes seem to indicate that psycopg2 was added in 0.7.7

Ive been trying to track down source of this issue and see that  pg_config is installed on the target machine and available from command shell, yet doesn't appear to be available to pip3?

```
TASK [lae.netbox : Install psycopg2/selinux via pip on Red Hat-based distros] ***
[DEPRECATION WARNING]: Invoking "pip" only once while using a loop via 
squash_actions is deprecated. Instead of using a loop to supply multiple items 
and specifying `name: "{{ item }}"`, please use `name: ['psycopg2', 'selinux']`
 and remove the loop. This feature will be removed in version 2.11. Deprecation
 warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
failed: [stg001] (item=['psycopg2', 'selinux']) => {"changed": false, "cmd": ["/usr/local/bin/pip3", "install", "-U", "psycopg2", "selinux"], "item": ["psycopg2", "selinux"], "msg": "stdout: Collecting psycopg2\n  Using cached https://files.pythonhosted.org/packages/23/7e/93c325482c328619870b6cd09370f6dbe1148283daca65115cd63642e60f/psycopg2-2.8.2.tar.gz\n    Complete output from command python setup.py egg_info:\n    running egg_info\n    creating pip-egg-info/psycopg2.egg-info\n    writing pip-egg-info/psycopg2.egg-info/PKG-INFO\n    writing dependency_links to pip-egg-info/psycopg2.egg-info/dependency_links.txt\n    writing top-level names to pip-egg-info/psycopg2.egg-info/top_level.txt\n    writing manifest file 'pip-egg-info/psycopg2.egg-info/SOURCES.txt'\n    \n    Error: pg_config executable not found.\n    \n    pg_config is required to build psycopg2 from source.  Please add the directory\n    containing pg_config to the $PATH or specify the full executable path with the\n    option:\n    \n        python setup.py build_ext --pg-config /path/to/pg_config build ...\n    \n    or with the pg_config option in 'setup.cfg'.\n    \n    If you prefer to avoid building psycopg2 from source, please install the PyPI\n    'psycopg2-binary' package instead.\n    \n    For further information please check the 'doc/src/install.rst' file (also at\n    <http://initd.org/psycopg/docs/install.html>).\n    \n    \n    ----------------------------------------\n\n:stderr: Command \"python setup.py egg_info\" failed with error code 1 in /tmp/pip-install-gwcflx76/psycopg2/\n
```

**Comment by madeinoz67** [comment]
further to this while troubleshooting;

pg_config is definitely included in the current path 

manual upgrade of psycopg2 works 

```
pip3 install --upgrade psycopg2
Collecting psycopg2
  Using cached https://files.pythonhosted.org/packages/23/7e/93c325482c328619870b6cd09370f6dbe1148283daca65115cd63642e60f/psycopg2-2.8.2.tar.gz
Installing collected packages: psycopg2
  Found existing installation: psycopg2 2.7.7
    Uninstalling psycopg2-2.7.7:
      Successfully uninstalled psycopg2-2.7.7
  Running setup.py install for psycopg2 ... done
Successfully installed psycopg2-2.8.2
```

after manual upgrade role successfully runs

**Comment by lae** [comment]
psycopg2 was not added in 0.7.7 - the selinux library was (9ecd71d17f587940aaa18ed9c02eb90960506c47). NetBox needs psycopg2 in the first place to run.

Can you give me the output of `which pg_config` on the host and the ad-hoc command `ansible -i $host, all -m shell -a 'echo $PATH'` (replace `$host` with your box)?

**Comment by madeinoz67** [comment]
```
ansible -i netbox, all -m shell -a 'echo $PATH'
netbox | CHANGED | rc=0 >>
/usr/local/bin:/usr/bin:/usr/pgsql-9.6/bin:/opt/stack/bin:/opt/stack/sbin

```

as a side note, while I mentioned above that if I ran the pip upgrade manually the task completed, while it successfully completed it broke the netbox installation, I'm just trying to track down the reason, however appears to be redis service related

**Comment by madeinoz67** [comment]
A work around for this is to use the package psycopg2-binary which is already pre-compiled

**Comment by lae** [comment]
I was thinking that replacing the dependency with the binary version would fix it, but I'm still a bit surprised that no errors get thrown during any of the tests with regards to this.

**Comment by madeinoz67** [comment]
It seems to be a real edge case on the machine its failing and I still haven't found the root cause.  ¯\_(ツ)_/¯
