### ISSUE TITLE
NetBox 2.6 support

### ISSUE THREAD

**Issue by lae** [lae/ansible-role-netbox#52]
2.6 looks like it requires Redis setup and configuration, and maybe some other things. I started a branch at https://github.com/lae/ansible-role-netbox/tree/feature/netbox-2.6 but if anyone wants to contribute, please feel free.

**Comment by madeinoz67** [comment]
happy to help and will work off that branch

**Comment by lae** [comment]
@madeinoz67 thanks! I've added you as a collaborator so feel free to push directly to that branch.

**Comment by lae** [comment]
@madeinoz67 did you make any progress on this? I noticed 2.6 was released not too long ago so want to get around to cutting a release soon.

**Comment by madeinoz67** [comment]
no sorry Ive been acting manager since then have have absolutely no time to scratch myself, the new manager has started so once I hand over I'll squeeze in some time.

**Comment by lae** [comment]
@madeinoz67 okay, don't feel too obligated - just wanted to check in case you had any uncommitted changes. @corny seems to have opened a PR (albeit it's a bit incomplete for my liking wrt redis) so I'll try to make some time this weekend to review the release upstream/identify what's missing from his PR.

**Comment by madeinoz67** [comment]
No I do fee obligated as I did commit myself to helping ... just timing wasn't so great sigh!  sorry about that.

**Comment by corny** [comment]
@lae  Please let me know if anything is missing.

**Comment by lae** [comment]
Completed in #61.
