### ISSUE TITLE
uwsgi.ini config customization

### ISSUE THREAD

**Issue by roland-github** [lae/ansible-role-netbox#60]
Hi,

we are experiencing uWSGI errors when using apache proxy in front of it, like below:
` [WARNING] unable to add HTTP_CONNECTION=Keep-Alive to uwsgi packet, consider increasing buffer size`
And 502 error in apache proxy.
It happens usually when posting via apache proxy, actions like import vlan list or create new user (in case of ldap auth configured in netbox).
uWSGI  mention in it's docs that it's default buffer size is a bit small:
> By default uWSGI allocates a very small buffer (4096 bytes) for the headers of each request. If you start receiving “invalid request block size” in your logs, it could mean you need a bigger buffer. Increase it (up to 65535) with the buffer-size option.

We would like a possibility to pass the buffer size setting as variable when running your netbox role, like below config line:
`buffer-size=65535`

Centos7/pip3/uWSGI (2.0.18)/netbox-2.5.12

Thank you

**Comment by lae** [comment]
An "extra uwsgi options" list role variable that gets parsed into the uwsgi template should work for this, I believe?

**Comment by roland-github** [comment]
yes, that would be the best.

thanks
