### ISSUE TITLE
Add HTTPS and letsencrypt compatibility.

### ISSUE THREAD

**Issue by lucasmaurice** [lae/ansible-role-netbox#62]

**Comment by tyler-8** [comment]
There's nothing inherent to this role that would require special tuning to have HTTPS & LetsEncrypt in your NetBox environment. There are many many dozens of examples on configuring HTTPS and LetsEncrypt out there, and plenty of Ansible roles to handle that functionality for you. Building an example in to this repo would just add another item that will get outdated and have to be maintained.
