### ISSUE TITLE
Add support for Netbox metrics configurations

### ISSUE THREAD

**Issue by tyler-8** [lae/ansible-role-netbox#68]
When using the built-in metrics for Netbox (based on `django-prometheus`), there are a couple new configuration items that need to be added across the project.

The `systemd` service file would need this parameter set (to auto-create the metrics storage folder in `/run` on boot):

```
[Service]
{% if netbox_metrics_enabled %}
RuntimeDirectory={{ netbox_metrics_dir }}
{% endif %}
```

`uwsgi.ini` - This whole line can be set by the user already using `netbox_uwsgi_options`
```
[uwsgi]
env=prometheus_multiproc_dir=/run/{{ netbox_metrics_dir }}
```

So depending on your preference it may really just be a case of adding the new template snippet to `netbox.service.j2`

**Comment by lae** [comment]
That method looks fine to me. Do you want to open a PR?

**Comment by tyler-8** [comment]
Yes - I'll put one together
