### ISSUE TITLE
RHEL 8 / Centos 8 Support 

### ISSUE THREAD

**Issue by eawain** [lae/ansible-role-netbox#71]
Any chance we can get this role updated for RHEL 8 / Centos 8 ? 
Busy looking at migrating an old NetBox Centos 6 install to Centos 8

**Comment by lae** [comment]
I think the definition in `redhat/vars.yml` may or may not cover RHEL 8, haven't tested (I'm guessing EPEL probably contains something newer than python 3.6 for RHEL 8 so it might be necessary to split the definition up again).

The test suite I'm using currently doesn't support CentOS 8 and requires some more heavy changes (https://github.com/lae/ansible-role-travis-lxc/issues/43#issuecomment-555092841). It might be a while until I can get to officially supporting RHEL/CentOS 8 in this role.

**Comment by eawain** [comment]
Thanks mate .
I'll give it a whirl again today. I had to make my own RedHat-8.yml vars file in postgres and was hitting a bit of a wall there.

**Comment by lae** [comment]
Is the role erroring out with something actionable? Lack of testing doesn't mean I can't accept changes to get the role working on RHEL 8 - it just means that I won't be comfortable saying this role works on it if I don't have tests regularly ran for it.
