### ISSUE TITLE
Netbox 2.7 Remote File Systems

### ISSUE THREAD

**Issue by kdhlab** [lae/ansible-role-netbox#78]
Netbox 2.7 introduced the ability to utilize Django storages for the file system.
https://django-storages.readthedocs.io/en/stable/
https://netbox.readthedocs.io/en/stable/configuration/optional-settings/#storage_backend

I think the best way to handle this for the role is to keep the critical files local, and only really move the scripts, media, and reports off to the remote storage provider. 

Additionally due to the number of variables in utilizing these providers I think we should probably keep the roles implementation of this as simple as possible by allowing the user to declare their json in a separate file, and having the role inject the end-users json straight into the config.py.

I wrote some code demonstrating my concept today, but due to not being able to utilize all the possible providers I am not sure how we would even go about testing all the possibilities.

Thoughts?

**Comment by lae** [comment]
This is mentioned in #67 and is a blocker for me before I cut 2.7 support.

I was about to look into implementing this later today actually, so thanks for bringing this up/working on it. If the configuration for those storage methods are all JSON anyway, shouldn't it be possible to specify them in YAML and then use the JSON filter when dumping the config? (Similar to what we do for the `netbox_config` role variable)

**Comment by lae** [comment]
Took a look at #79. The constraints file doesn't behave like a requirements file - so those packages won't be installed.

What I have in mind is a variable (not a default) that stores a dictionary containing the Python package requirement (e.g. boto, though maybe this is a default dependency of django-storages) and the pertinent django-storages module (`storages.backends.s3boto3.S3Boto3Storage`), and that variable would be accessed to configure the backend var and package install task.

Also, I don't think the storage feature in NetBox can selectively keep some files locally and some remotely? But it looks like it only gets used for uploaded files in the first place.

**Comment by kdhlab** [comment]
I looked at the django storages documentation again, and I could be wrong but it seems like if you just install django-storages it will install all the backends, or you can just install the one you want by specifying it. 

Considering this, and that I didn't really think about just using YAML and converting with the JSON filter before I refactored to make #79 as simple as possible. If you specify netbox_config.STORAGE_BACKEND then the module gets added to requirements text, which should be all that is required to make it work technically. If you do it that way, the only additional thing needed would probably be an example play to demonstrate the usage of inserting the storage provider into the YAML.

**Comment by lae** [comment]
Hm, do you have a link to where it says that about the backends? I just stood up a clean venv and it doesn't seem to have:

```
(storage-test) [lae@lilienne ~]$ pip install django-storages
Collecting django-storages
  Downloading https://files.pythonhosted.org/packages/cc/f2/c1ed8d741e8f6b96197f82bf0cb1451d6d7d2c702fb072cdfdf01746cfb7/django_storages-1.9.1-py2.py3-none-any.whl (42kB)
     |████████████████████████████████| 51kB 3.3MB/s 
Collecting Django>=1.11 (from django-storages)
  Downloading https://files.pythonhosted.org/packages/c6/b7/63d23df1e311ca0d90f41352a9efe7389ba353df95deea5676652e615420/Django-3.0.3-py3-none-any.whl (7.5MB)
     |████████████████████████████████| 7.5MB 6.9MB/s 
Collecting sqlparse>=0.2.2 (from Django>=1.11->django-storages)
  Downloading https://files.pythonhosted.org/packages/ef/53/900f7d2a54557c6a37886585a91336520e5539e3ae2423ff1102daf4f3a7/sqlparse-0.3.0-py2.py3-none-any.whl
Collecting pytz (from Django>=1.11->django-storages)
  Downloading https://files.pythonhosted.org/packages/e7/f9/f0b53f88060247251bf481fa6ea62cd0d25bf1b11a87888e53ce5b7c8ad2/pytz-2019.3-py2.py3-none-any.whl (509kB)
     |████████████████████████████████| 512kB 9.0MB/s 
Collecting asgiref~=3.2 (from Django>=1.11->django-storages)
  Downloading https://files.pythonhosted.org/packages/a5/cb/5a235b605a9753ebcb2730c75e610fb51c8cab3f01230080a8229fa36adb/asgiref-3.2.3-py2.py3-none-any.whl
Installing collected packages: sqlparse, pytz, asgiref, Django, django-storages
Successfully installed Django-3.0.3 asgiref-3.2.3 django-storages-1.9.1 pytz-2019.3 sqlparse-0.3.0
WARNING: You are using pip version 19.2.3, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

Checking for `netbox_config.STORAGE_BACKEND` is an okay alternative I suppose. But given the above, I think it might be necessary to check what it's defined to and install the appropriate package.

Also, modifying the requirements file directly is likely to cause file conflicts when updating git-based installations. For extra packages we've just been using the pip module - but it looks like this'll be the third one. This might be a good chance to consolidate those into one task, like this `apt` task: https://github.com/lae/ansible-role-netbox/blob/master/tasks/install_packages_apt.yml#L9

**Comment by kdhlab** [comment]
Yep, you are right. My test environment installs the azure module as part of the build so that threw me off. If you install the azure module first it satisfies the django storages dependencies.

This is on a completely clean rhel box:
```
[root@netbox ~]# pip3 install django-storages
Collecting django-storages
  Downloading django_storages-1.9.1-py2.py3-none-any.whl (42 kB)
     |████████████████████████████████| 42 kB 810 kB/s 
Collecting Django>=1.11
  Downloading Django-3.0.3-py3-none-any.whl (7.5 MB)
     |████████████████████████████████| 7.5 MB 5.0 MB/s 
Collecting sqlparse>=0.2.2
  Downloading sqlparse-0.3.0-py2.py3-none-any.whl (39 kB)
Collecting asgiref~=3.2
  Downloading asgiref-3.2.3-py2.py3-none-any.whl (18 kB)
Collecting pytz
  Downloading pytz-2019.3-py2.py3-none-any.whl (509 kB)
     |████████████████████████████████| 509 kB 21.7 MB/s 
Installing collected packages: sqlparse, asgiref, pytz, Django, django-storages
Successfully installed Django-3.0.3 asgiref-3.2.3 django-storages-1.9.1 pytz-2019.3 sqlparse-0.3.0
[root@netbox ~]# pip3 install django-storages[azure]
Requirement already satisfied: django-storages[azure] in /usr/local/lib/python3.6/site-packages (1.9.1)
Requirement already satisfied: Django>=1.11 in /usr/local/lib/python3.6/site-packages (from django-storages[azure]) (3.0.3)
Collecting azure-storage-blob<12.0.0,>=1.3.1; extra == "azure"
  Downloading azure_storage_blob-2.1.0-py2.py3-none-any.whl (88 kB)
     |████████████████████████████████| 88 kB 2.5 MB/s 
Requirement already satisfied: sqlparse>=0.2.2 in /usr/local/lib/python3.6/site-packages (from Django>=1.11->django-storages[azure]) (0.3.0)
Requirement already satisfied: asgiref~=3.2 in /usr/local/lib/python3.6/site-packages (from Django>=1.11->django-storages[azure]) (3.2.3)
Requirement already satisfied: pytz in /usr/local/lib/python3.6/site-packages (from Django>=1.11->django-storages[azure]) (2019.3)
Collecting azure-common>=1.1.5
  Downloading azure_common-1.1.24-py2.py3-none-any.whl (12 kB)
Collecting azure-storage-common~=2.1
  Downloading azure_storage_common-2.1.0-py2.py3-none-any.whl (47 kB)
     |████████████████████████████████| 47 kB 13.3 MB/s 
Collecting python-dateutil
  Downloading python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
     |████████████████████████████████| 227 kB 6.0 MB/s 
Collecting cryptography
  Downloading cryptography-2.8-cp34-abi3-manylinux2010_x86_64.whl (2.3 MB)
     |████████████████████████████████| 2.3 MB 40.6 MB/s 
Collecting requests
  Downloading requests-2.22.0-py2.py3-none-any.whl (57 kB)
     |████████████████████████████████| 57 kB 15.6 MB/s 
Collecting six>=1.5
  Downloading six-1.14.0-py2.py3-none-any.whl (10 kB)
Collecting cffi!=1.11.3,>=1.8
  Downloading cffi-1.14.0-cp36-cp36m-manylinux1_x86_64.whl (399 kB)
     |████████████████████████████████| 399 kB 36.2 MB/s 
Collecting certifi>=2017.4.17
  Downloading certifi-2019.11.28-py2.py3-none-any.whl (156 kB)
     |████████████████████████████████| 156 kB 22.9 MB/s 
Collecting chardet<3.1.0,>=3.0.2
  Downloading chardet-3.0.4-py2.py3-none-any.whl (133 kB)
     |████████████████████████████████| 133 kB 16.4 MB/s 
Collecting idna<2.9,>=2.5
  Downloading idna-2.8-py2.py3-none-any.whl (58 kB)
     |████████████████████████████████| 58 kB 13.3 MB/s 
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1
  Downloading urllib3-1.25.8-py2.py3-none-any.whl (125 kB)
     |████████████████████████████████| 125 kB 39.6 MB/s 
Collecting pycparser
  Downloading pycparser-2.19.tar.gz (158 kB)
     |████████████████████████████████| 158 kB 37.6 MB/s 
Installing collected packages: azure-common, six, python-dateutil, pycparser, cffi, cryptography, certifi, chardet, idna, urllib3, requests, azure-storage-common, azure-storage-blob
    Running setup.py install for pycparser ... done
Successfully installed azure-common-1.1.24 azure-storage-blob-2.1.0 azure-storage-common-2.1.0 certifi-2019.11.28 cffi-1.14.0 chardet-3.0.4 cryptography-2.8 idna-2.8 pycparser-2.19 python-dateutil-2.8.1 requests-2.22.0 six-1.14.0 urllib3-1.25.8
[root@netbox ~]# 
```

So yeah, hashtable it is. For simplicity's sake you could still key off the `netbox_config.STORAGE_BACKEND` value so you don't need another variable.
