### ISSUE TITLE
Does anyone use Redis Sentinel?

### ISSUE THREAD

**Issue by lae** [lae/ansible-role-netbox#83]
Background: https://github.com/netbox-community/netbox/issues/3984

This'll require some mucking about with the Redis connection role variables again, but I'm not sure if there's value in implementing support for this. Does anyone use Sentinel and have a need for being able to configure NetBox/Django accordingly?

**Comment by madeinoz67** [comment]
I’m not currently using sentinel and haven’t really thought of a need so answer for me is not at this time.

**Comment by lae** [comment]
Doesn't seem like there's any other interest, so closing.
